apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ahmedkhabkhab/dispatcher-service/k8s?ref=master

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: dispatcher-config
images:
  - name: dispatcher-service
    newName: ghcr.io/ahmedkhabkhab/dispatcher-service
    newTag: latest

replicas:
  - name: dispatcher-service
    count: 2