apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog-service
  name: catalog-service
spec:
  ports:
  - name: 80-9001
    port: 80
    protocol: TCP
    targetPort: 9001
  selector:
    app: catalog-service
  type: ClusterIP
