apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ahmedkhabkhab/catalog-service/k8s?ref=42fc05a487fc72c3452f40e8c63b8057b3b120c8

patchesStrategicMerge:
  - patch-env.yml
  - patch-volumes.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-prod.yml
    name: catalog-config
images:
  - name: catalog-service
    newName: ghcr.io/ahmedkhabkhab/catalog-service
    newTag: 42fc05a487fc72c3452f40e8c63b8057b3b120c8